# -*- coding: utf-8 -*-
"""Practica-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSVKvBnjJtzM3jRN9jZwOXK69F65fZOU

# 1) Veamos los datos
"""

# modulo que usaremos
import pandas as pd
import numpy as np

# Leer en todos nuestros datos
sf_permits = pd.read_csv("../content/Building_Permits.csv")

# set seed for reproducibility
np.random.seed(0)

sf_permits.head()

"""¿El conjunto de datos tiene valores faltantes? La respuesta es si, a continuación mostramos la cantidad de datos faltantes que existen en este set de datos."""

missing_values_count = sf_permits.isnull().sum()
missing_values_count[0:43]

total_cells = np.product(sf_permits.shape)
total_missing = missing_values_count.sum()

print(total_cells)
print("Total de datos faltantes: ",total_missing)

"""# 2) ¿Qué porcentaje de los valores en el conjunto de datos faltan?
La respuesta es 25.5 %
"""

percent_missing = (total_missing/total_cells)*100
print(percent_missing)

"""# 3) Averiguar por qué faltan los datos
¿Cuáles, si es que faltan, por qué no existen?
Los datos de **Street Number Suffix** porque la mayoría de las casas no existe un sufijo de su numero, entonces este atributo no existe.

¿Cuales si es que faltan por qué no se registraron?
**Zipcode**,  hay filas en las que la mayoría de información de los atributos es nula así que es dificil saber el zipcode de las direcciones.

"""

subset_sf_permits = sf_permits.loc[:,'Street Number Suffix':'Zipcode'].head()
subset_sf_permits

display(sf_permits)