# -*- coding: utf-8 -*-
"""practica-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEbbe7EwcHmGoT1AbAZDiDPSGfaDNXY-

# Transformación de Fechas
## Pandas - to_datetime()
Cosijoeza Melchor Nolasco - Universidad Técnologica de la Mixteca

Maestría en Ciencia de Datos

Esta practica nos muestra cómo parsear datos de tipo 'objeto' a datos de tipo 'datetime64'.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import datetime

"""## Datos
Se leen los datos desde un archivo con formato csv y se revisa cómo vienen.
"""

landslides = pd.read_csv("sample_data/catalog.csv")
np.random.seed(0)

landslides.head()

print(landslides['date'].head())

landslides['date'].dtype

"""## Transformación de los datos
Debido a que los datos de la columna 'date' están definidos como un tipo 'objeto', se van a transformar en el tipo de dato 'fecha y hora'.

%d para el día, %m para el mes, %y para un año de dos dígitos y %Y para un año de cuatro dígitos.

Algunos ejemplos:

17/01/07 tiene el formato "%m/%d/%y"

17-1-2007 tiene el formato "%d-%m-%Y"
"""

landslides['date_parsed'] = pd.to_datetime(landslides['date'],format="%m/%d/%y")

"""Los datos quedan de la siguiente manera."""

landslides['date_parsed'].head()

"""## Trazar el día del mes para comprobar el analisis de la fecha
Se extraen solamente los días de la nueva columna través del metodo `dt.day`.
"""

dayOfMonthLandslides = landslides['date_parsed'].dt.day
dayOfMonthLandslides.head()

"""Trazamos un histograma de los días del mes. Esperamos que tenga valores entre 1 y 31.
Se puede observar que se está obteniendo valores de acuerdo a lo que se buscó.
"""

dayOfMonthLandslides = dayOfMonthLandslides.dropna()
sns.histplot(dayOfMonthLandslides,kde=False,bins=31)